# fly.toml app configuration file generated for sonoria on 2024-05-01T21:39:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sonoria'
primary_region = 'mad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'mysql'
  DB_DATABASE = 'defaultdb'
  DB_HOST = 'mysql-116d65cf-sonoria.b.aivencloud.com'
  DB_PASSWORD = 'AVNS_5YjmFAv1eNyWPQ6A4BA'
  DB_PORT = '25801'
  DB_USERNAME = 'avnadmin'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
